// This file is generated by Velite

import config from '../velite.config'

type Collections = typeof config.collections

export type Docs = Collections['docs']['schema']['_output']
export declare const docs: Docs[]
